# Generated by Django 3.2.9 on 2022-02-09 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, verbose_name='Наименование товара')),
                ('total', models.PositiveBigIntegerField(verbose_name='Сумма сделки')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество товара,шт')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время регистрации сделки')),
            ],
            options={
                'verbose_name': 'сделка',
                'verbose_name_plural': 'сделки',
                'ordering': ('-date',),
            },
        ),
    ]
