# Generated by Django 3.2.9 on 2022-02-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-spent_money',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
